app = "leapfound-app-naijal"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_NAME = "Leapfound"
  APP_ENV = "prod"
  PORT = "8000"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 2
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 50
    hard_limit = 100
[checks]
  [checks.http]
    port = 8000
    type = "http"
    interval = "15s"
    timeout = "5s"
    grace_period = "60s"
    method = "GET"
    path = "/health"
